# k8s/service-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <IMAGE_TAG_FRONTEND> # Pipeline injects: acr/frontend:v1.0.0
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-api-service"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  annotations:
    # Azure specific annotation to expose a Standard Load Balancer
    service.beta.kubernetes.io/azure-load-balancer-resource-group: $(resource_group_name) # Uses the RG created by Terraform
spec:
  type: LoadBalancer # Creates an Azure Standard Load Balancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend